server:
  port: 8080
  context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_rbac
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
